package com.bookstorereactive.domain;

public enum BookGenre {
    FICTION, DRAMA, ROMANCE, SCIENCE_FICTION, FANTASY, HORROR, DOCUMENTARY, PSYCHOLOGICAL, POETRY, THRILLER, HISTORICAL_FICTION, BIOGRAPHY, MYSTERY, SCIENCE
}
